services:
  client:
    container_name: client
    build: .
    ports:
      - "3000:3000"
<<<<<<< HEAD
    # volumes:
    #   - .:/app
=======
    #volumes:
    #  - .:/app
>>>>>>> f4a5c300d7bd5a25d1a679e8dd8d3176c9368a4c
    command: sh -c "npm run dev && npm run start"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all", "--nounixsocket"]
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: